apiVersion: apps/v1
kind: Deployment
metadata:
  name: appkube
spec:
  selector:
    matchLabels:
      app: appkube
  replicas: 2
  template:
    metadata:
      labels:
        app: appkube
    spec:
      containers:
        - name: appkube
          image: werty2012/appdocker:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: appkube
spec:
  selector:
    app: appkube
  ports:
    - protocol: TCP
      port: 8000